# Generated by Django 3.0.7 on 2020-06-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='long',
        ),
        migrations.AddField(
            model_name='district',
            name='image_source',
            field=models.TextField(default='rachit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=1.1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='long',
            field=models.DecimalField(decimal_places=8, default=1.1, max_digits=20),
            preserve_default=False,
        ),
    ]
