# Generated by Django 3.0.7 on 2020-06-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0002_auto_20200606_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='mapping',
            field=models.TextField(default='asaam'),
            preserve_default=False,
        ),
    ]
