# Generated by Django 3.0.7 on 2020-06-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0005_auto_20200607_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name_district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ghumakkad.Place'),
        ),
    ]
