# Generated by Django 3.0.7 on 2020-06-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0007_auto_20200607_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ghumakkad.District'),
        ),
    ]
