# Generated by Django 3.0.7 on 2020-06-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0009_auto_20200607_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name_district',
            field=models.CharField(max_length=50),
        ),
    ]
