# Generated by Django 3.0.7 on 2020-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0010_auto_20200607_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='state',
            field=models.CharField(default='awesome', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.CharField(default='awesome', max_length=50),
            preserve_default=False,
        ),
    ]
