# Generated by Django 3.0.7 on 2020-06-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0011_auto_20200610_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='long',
            new_name='longi',
        ),
    ]
