# Generated by Django 3.0.7 on 2020-06-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0013_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.FileField(default='a.pdf', upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
    ]
