# Generated by Django 3.0.7 on 2020-06-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0014_auto_20200611_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.FileField(upload_to='blog'),
        ),
    ]
