# Generated by Django 3.0.7 on 2020-06-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0015_auto_20200611_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
    ]
