# Generated by Django 3.0.7 on 2020-06-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0017_auto_20200612_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
    ]
