# Generated by Django 3.0.7 on 2020-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0018_auto_20200613_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo',
            field=models.TextField(default='gfdg'),
            preserve_default=False,
        ),
    ]
