# Generated by Django 3.0.7 on 2020-06-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghumakkad', '0019_place_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='mapping',
        ),
    ]
